### ISSUE TITLE
RitoKit no longer on cocoapods

### ISSUE THREAD

**Issue by rdrnt** [levi/RitoKit#1]
I'm either going crazy, or RitoKit is hiding from me. I can't seem to find it on cocapods anywhere.

**Comment by levi** [comment]
Hrm, that's strange. It's been a while since I've updated RitoKit and I'd recommend just pointing directly to the git repo to install the pod.

**Comment by rdrnt** [comment]
Thanks, sadly nothing I try seems to work, guess it needs some updating :(
